[theme]
primaryColor = "#D4AF37"
backgroundColor = "#0A0A0F"
secondaryBackgroundColor = "#12121A"
textColor = "#D6E7F2"
font = "sans serif"

[server]
enableStaticServing = true
headless = true

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true